import { Link, Navigate, useParams } from 'react-router-dom'
import { componentNavigation } from '../navigation'
import { CodeBlock } from '../components/CodeBlock'
import { DocsSection, PageIntro } from '../components/DocsSection'
import { componentDocsBySlug } from '../content/components'

export function ComponentPage() {
  const { slug } = useParams()
  const documentation = slug ? componentDocsBySlug.get(slug) : undefined
  if (!documentation) return <Navigate to="/docs/not-found" replace />

  return <><PageIntro eyebrow="Component" title={documentation.title} summary={documentation.summary} /><DocsSection id="purpose" title="Purpose and recommended use"><ul>{documentation.useCases.map((item) => <li key={item}>{item}</li>)}</ul></DocsSection><DocsSection id="import" title="Import"><CodeBlock code={documentation.importCode} label="Import" /></DocsSection><DocsSection id="usage" title="Basic usage"><CodeBlock code={documentation.basicCode} /></DocsSection><DocsSection id="examples" title="Live example"><div className="rounded-lg border border-border-secondary bg-surface-primary p-lg sm:p-xl">{documentation.example}</div></DocsSection><DocsSection id="api" title="Props and API"><div className="overflow-x-auto rounded-lg border border-border-secondary"><table className="w-full min-w-[44rem] border-collapse text-left text-body-sm"><thead className="bg-table-header-background text-label-sm text-text-secondary"><tr><th className="border-b border-table-border p-md">Prop</th><th className="border-b border-table-border p-md">Type</th><th className="border-b border-table-border p-md">Default</th><th className="border-b border-table-border p-md">Description</th></tr></thead><tbody>{documentation.props.map((prop) => <tr key={prop.name}><th scope="row" className="border-b border-table-border p-md font-semibold text-text-primary"><code>{prop.name}</code></th><td className="border-b border-table-border p-md"><code>{prop.type}</code></td><td className="border-b border-table-border p-md"><code>{prop.defaultValue ?? '—'}</code></td><td className="border-b border-table-border p-md">{prop.description}</td></tr>)}</tbody></table></div></DocsSection><DocsSection id="variants" title="Variants, sizes, and states"><ul>{documentation.variants.map((item) => <li key={item}>{item}</li>)}</ul></DocsSection><DocsSection id="accessibility" title="Accessibility and keyboard behavior"><ul>{documentation.accessibility.map((item) => <li key={item}>{item}</li>)}</ul></DocsSection><DocsSection id="responsive" title="Responsive and theme behavior"><p>{documentation.responsive}</p><p>{documentation.theme}</p></DocsSection><DocsSection id="recommendations" title="Common mistakes and recommendations"><ul>{documentation.mistakes.map((item) => <li key={item}>{item}</li>)}</ul></DocsSection><DocsSection id="related" title="Related components"><div className="flex flex-wrap gap-sm">{documentation.related.map((relatedSlug) => { const item = componentNavigation.find((entry) => entry.slug === relatedSlug); return item ? <Link key={item.path} to={item.path} className="rounded-md border border-border-primary bg-surface-primary px-md py-sm no-underline hover:border-border-focus">{item.title}</Link> : null })}</div></DocsSection></>
}
