import { componentExamples } from './examples'
import { type ComponentDocumentation, type PropReference } from './types'

const classNameProp: PropReference = { name: 'className', type: 'string', description: 'Adds styling at the component boundary without replacing semantic defaults.' }

const createDoc = (documentation: Omit<ComponentDocumentation, 'example'>): ComponentDocumentation => ({
  ...documentation,
  example: componentExamples[documentation.slug],
})

export const componentDocs = [
  createDoc({
    slug: 'button', title: 'Button', summary: 'Triggers one immediate action with a clear hierarchy and complete keyboard semantics.',
    useCases: ['Commit a form or focused task.', 'Expose a supporting, low-emphasis, destructive, toggle, or disclosure action.'],
    importCode: "import { Button } from '@/components'",
    basicCode: `<Button variant="primary" onClick={save}>Save changes</Button>`,
    props: [
      { name: 'variant', type: "'primary' | 'secondary' | 'tertiary' | 'destructive'", defaultValue: "'primary'", description: 'Sets the semantic action hierarchy.' },
      { name: 'size', type: "'sm' | 'md' | 'icon'", defaultValue: "'md'", description: 'Uses compact, standard, or square icon sizing.' },
      { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Exposes busy state and prevents repeat activation.' },
      { name: 'icon / iconPosition', type: "ReactNode / 'start' | 'end'", description: 'Adds a decorative icon before or after the label.' },
      { name: '…button props', type: 'ButtonHTMLAttributes<HTMLButtonElement>', description: 'Forwards native button attributes and event handlers.' }, classNameProp,
    ],
    variants: ['Primary, secondary, tertiary, and destructive hierarchy.', 'Compact, standard, and icon sizes.', 'Default, hover, focus, active, loading, disabled, pressed, and expanded states.'],
    accessibility: ['Uses a native button, so Enter and Space activate it.', 'Icon-only buttons need an accessible name.', 'Use aria-pressed for toggles and aria-expanded with aria-controls for disclosures.'],
    responsive: 'Use compact only in dense pointer-oriented tools. Standard and icon sizes preserve the touch target in touch contexts.',
    theme: 'Every variant uses semantic action tokens; focus remains visible in light and demo dark themes.',
    mistakes: ['Do not use a button for navigation.', 'Do not remove the label during loading.', 'Name the destructive outcome instead of relying on red.'],
    related: ['modal', 'dropdown'],
  }),
  createDoc({
    slug: 'input', title: 'Input', summary: 'Collects short, structured text with persistent guidance and validation.',
    useCases: ['Names, email addresses, search, codes, dates, and other single-line values.'], importCode: "import { Input } from '@/components'", basicCode: `<Input label="Project name" helperText="Visible to your team." />`,
    props: [{ name: 'label', type: 'string', description: 'Required visible and accessible label.' }, { name: 'size', type: "'compact' | 'standard'", defaultValue: "'standard'", description: 'Controls density.' }, { name: 'variant', type: "'default' | 'search'", defaultValue: "'default'", description: 'Applies standard or utility-search surface styling.' }, { name: 'helperText / error', type: 'string', description: 'Connects persistent guidance or the current error.' }, { name: 'status', type: "'default' | 'success' | 'warning' | 'invalid'", defaultValue: "'default'", description: 'Selects a semantic boundary and message state.' }, { name: '…input props', type: 'InputHTMLAttributes<HTMLInputElement>', description: 'Forwards type, autocomplete, required, readOnly, disabled, and native events.' }, classNameProp],
    variants: ['Standard, compact, and search.', 'Empty, populated, read-only, invalid, warning, success, and disabled states.'], accessibility: ['The visible label is explicitly associated with the input.', 'Helper and error text use programmatic descriptions; errors expose invalid state.', 'Choose the correct native type and autocomplete value.'], responsive: 'Fields fill their container; labels, help, and errors wrap. Prefer standard height when touch input is expected.', theme: 'Surface, text, border, disabled, validation, and focus roles are semantic tokens.', mistakes: ['A placeholder is not a label.', 'Do not use disabled when a value should remain focusable and copyable.', 'Do not erase the value during validation.'], related: ['textarea', 'select', 'combobox'],
  }),
  createDoc({
    slug: 'textarea', title: 'Textarea', summary: 'Collects plain multi-line text while preserving line breaks and resize access.', useCases: ['Descriptions, notes, feedback, and other values where line breaks matter.'], importCode: "import { Textarea } from '@/components'", basicCode: `<Textarea label="Description" maxLength={240} />`,
    props: [{ name: 'label', type: 'string', description: 'Required visible label.' }, { name: 'autoGrow', type: 'boolean', defaultValue: 'false', description: 'Signals a content-growing treatment while retaining resize access.' }, { name: 'helperText / error', type: 'string', description: 'Persistent guidance or current validation error.' }, { name: 'status', type: 'FieldStatus', defaultValue: "'default'", description: 'Semantic validation state.' }, { name: '…textarea props', type: 'TextareaHTMLAttributes<HTMLTextAreaElement>', description: 'Forwards maxLength, rows, required, readOnly, disabled, and native events.' }, classNameProp],
    variants: ['Resizable fixed-height and bounded content-growing treatments.', 'Read-only, invalid, warning, success, busy, and disabled states.'], accessibility: ['Uses a native textarea with explicit label and descriptions.', 'Character limits remain exposed through the native maxLength contract.', 'Browser resize behavior remains available.'], responsive: 'Fills available form width and lets labels, counts, long text, and errors wrap.', theme: 'Uses the text-field surface, boundary, focus, and validation roles.', mistakes: ['Do not use for formatted rich text.', 'Do not silently truncate at the character limit.', 'Do not disable resizing without an equivalent way to reach content.'], related: ['input'],
  }),
  createDoc({
    slug: 'select', title: 'Select', summary: 'Chooses one value from a stable set using the platform-native selection control.', useCases: ['Moderately sized predetermined lists that do not need filtering.'], importCode: "import { Select } from '@/components'", basicCode: `<Select label="Status" options={[{ value: 'active', label: 'Active' }]} />`,
    props: [{ name: 'label', type: 'string', description: 'Required visible label.' }, { name: 'options', type: 'readonly SelectOption[]', description: 'Values, labels, and optional disabled state.' }, { name: 'placeholder', type: 'string', description: 'Optional prompt; it is not a selected value when required.' }, { name: 'size', type: "'compact' | 'standard'", defaultValue: "'standard'", description: 'Controls density.' }, { name: 'helperText / error', type: 'string', description: 'Associated guidance or validation.' }, { name: '…select props', type: 'SelectHTMLAttributes<HTMLSelectElement>', description: 'Forwards native value, defaultValue, onChange, required, and disabled.' }, classNameProp],
    variants: ['Compact and standard native selects.', 'Unselected, selected, focus, invalid, and disabled states.'], accessibility: ['Native select semantics expose name, choices, value, and keyboard behavior.', 'The visible label and descriptions are explicitly related.', 'Disabled options remain visible but unavailable.'], responsive: 'The control stays within its container; option rendering follows the platform.', theme: 'Uses semantic field surfaces, validation borders, text, and focus.', mistakes: ['Use RadioGroup when a short list benefits from simultaneous visibility.', 'Use Combobox when filtering or text entry is needed.', 'Do not treat placeholder copy as a valid required value.'], related: ['radio-group', 'combobox', 'listbox'],
  }),
  createDoc({
    slug: 'listbox', title: 'Listbox', summary: 'Presents a visible list of selectable values with managed active-option navigation.', useCases: ['Persistent or popup single selection.', 'Multiple selection where options need simultaneous visibility.'], importCode: "import { Listbox } from '@/components'", basicCode: `<Listbox label="Owners" options={people} multiple />`,
    props: [{ name: 'label', type: 'string', description: 'Accessible visible name.' }, { name: 'options', type: 'readonly ListboxOption[]', description: 'Selectable values, labels, descriptions, and disabled state.' }, { name: 'multiple', type: 'boolean', defaultValue: 'false', description: 'Enables independent multi-selection.' }, { name: 'value / defaultValue', type: 'string | readonly string[]', description: 'Controlled or initial selection.' }, { name: 'onValueChange', type: '(value: string | string[]) => void', description: 'Reports committed selection.' }, { name: 'loading / error', type: 'boolean / string', description: 'Exposes async and failure states.' }, classNameProp],
    variants: ['Single and multiple selection.', 'Active, selected, checked, disabled, loading, empty, and error states.'], accessibility: ['Arrow keys, Home, End, Enter, Space, and type-ahead are supported.', 'Active option and selected values are exposed separately.', 'The listbox owns one page tab stop through aria-activedescendant.'], responsive: 'The list scrolls internally when necessary while remaining within available width.', theme: 'Popup surface, selection, action-hover, focus, and disabled tokens retain state distinctions.', mistakes: ['Do not use listbox options for unrelated commands.', 'Do not confuse focus with selection.', 'Prefer a native select when it satisfies the task.'], related: ['select', 'combobox', 'dropdown'],
  }),
  createDoc({
    slug: 'combobox', title: 'Combobox', summary: 'Combines text entry with a filtered list of selectable suggestions.', useCases: ['Search and select from long directories.', 'Optional free-form entry with relevant suggestions.'], importCode: "import { Combobox } from '@/components'", basicCode: `<Combobox label="Owner" options={people} />`,
    props: [{ name: 'label', type: 'string', description: 'Required visible label.' }, { name: 'options', type: 'readonly ListboxOption[]', description: 'Suggestions and selectable values.' }, { name: 'value / defaultValue', type: 'string', description: 'Controlled or initial selected value.' }, { name: 'allowCustomValue', type: 'boolean', defaultValue: 'false', description: 'Allows a value outside the options.' }, { name: 'onValueChange', type: '(value: string) => void', description: 'Reports selected or custom value.' }, { name: 'loading / emptyMessage / error', type: 'boolean / string / string', description: 'Async, empty, and validation feedback.' }, classNameProp],
    variants: ['Selection-only and explicit free-form entry.', 'Collapsed, expanded, typing, loading, active, selected, empty, invalid, and disabled states.'], accessibility: ['Exposes combobox, listbox, expanded, controlled, autocomplete, and active-descendant relationships.', 'Native text editing keys remain available.', 'Arrow keys navigate active suggestions; Enter commits; Escape closes and restores policy.'], responsive: 'The anchored popup uses the field width and scrolls instead of clipping long result sets.', theme: 'Combines text-field tokens with the dropdown surface and listbox states.', mistakes: ['Do not accept arbitrary input unless the variant explicitly allows it.', 'Do not announce every arrow-key movement.', 'Use Select if editable filtering is unnecessary.'], related: ['input', 'select', 'listbox'],
  }),
  createDoc({
    slug: 'checkbox', title: 'Checkbox', summary: 'Represents an independent binary choice or one independent choice in a set.', useCases: ['Form options, bulk selection, or independent notification channels.'], importCode: "import { Checkbox } from '@/components'", basicCode: `<Checkbox label="Email notifications" defaultChecked />`,
    props: [{ name: 'label', type: 'string', description: 'Visible label that activates the input.' }, { name: 'description / error', type: 'string', description: 'Associated context or validation.' }, { name: 'indeterminate', type: 'boolean', defaultValue: 'false', description: 'Sets the native mixed summary state.' }, { name: '…input props', type: 'InputHTMLAttributes<HTMLInputElement>', description: 'Forwards checked, defaultChecked, onChange, required, and disabled.' }, classNameProp],
    variants: ['Unchecked, checked, and indeterminate.', 'Hover, focus, invalid, and disabled states.'], accessibility: ['Uses a native checkbox and native mixed DOM state.', 'The indicator and visible label share one touch-friendly target.', 'Shape and checkmark communicate state without color alone.'], responsive: 'Labels and descriptions wrap without breaking the activation relationship.', theme: 'Selected action, neutral boundary, disabled, validation, and focus roles are semantic.', mistakes: ['Indeterminate is a summary, not automatically a third submitted value.', 'Use RadioGroup for one mutually exclusive choice.', 'Do not separate the label from the target.'], related: ['radio-group', 'switch'],
  }),
  createDoc({
    slug: 'radio-group', title: 'Radio group', summary: 'Selects exactly one value from a short set whose options benefit from being visible together.', useCases: ['Billing interval, plan type, or another short mutually exclusive choice.'], importCode: "import { RadioGroup } from '@/components'", basicCode: `<RadioGroup label="Interval" options={intervals} />`,
    props: [{ name: 'label', type: 'string', description: 'Group legend and accessible name.' }, { name: 'options', type: 'readonly RadioOption[]', description: 'Values, labels, descriptions, and option availability.' }, { name: 'value / defaultValue', type: 'string', description: 'Controlled or initial selection.' }, { name: 'orientation', type: "'horizontal' | 'vertical'", defaultValue: "'vertical'", description: 'Changes layout without changing option order.' }, { name: 'onValueChange', type: '(value: string) => void', description: 'Reports the selected option.' }, { name: 'description / error', type: 'string', description: 'Group-level guidance or validation.' }, classNameProp],
    variants: ['Horizontal and vertical layouts.', 'Unselected, selected, focus, invalid, disabled option, and disabled group states.'], accessibility: ['Uses fieldset, legend, and native radios with one shared name.', 'Arrow-key behavior follows the browser and platform convention.', 'The selected state uses both shape and color.'], responsive: 'Choose vertical layout when labels wrap or horizontal space is constrained.', theme: 'Action-selected, neutral boundary, focus, disabled, and danger roles remain distinct.', mistakes: ['Do not use for a long compact list.', 'Do not give each option a different group name.', 'Do not reorder options visually.'], related: ['select', 'checkbox'],
  }),
  createDoc({
    slug: 'switch', title: 'Switch', summary: 'Changes a persistent setting between on and off, normally with immediate effect.', useCases: ['Settings that save immediately, such as notifications or visibility.'], importCode: "import { Switch } from '@/components'", basicCode: `<Switch label="Email notifications" defaultChecked />`,
    props: [{ name: 'label', type: 'string', description: 'Stable setting name; it does not change with state.' }, { name: 'description / error', type: 'string', description: 'Current consequence or failure message.' }, { name: 'busy', type: 'boolean', defaultValue: 'false', description: 'Exposes pending state and prevents duplicate changes.' }, { name: '…input props', type: 'InputHTMLAttributes<HTMLInputElement>', description: 'Forwards checked, defaultChecked, onChange, and disabled.' }, classNameProp],
    variants: ['Off and on.', 'Hover, focus, busy, error, and disabled states.'], accessibility: ['Exposes role switch and the native checked state.', 'Space toggles; the label activates the same control.', 'Position and shape supplement color.'], responsive: 'The row wraps or stacks naturally while preserving a minimum target.', theme: 'On, off, boundary, text, disabled, and focus states use semantic roles.', mistakes: ['Use Checkbox for a value committed by a later form submission.', 'Do not change the visible label between on and off.', 'Restore the prior state and explain async failures.'], related: ['checkbox', 'alert'],
  }),
  createDoc({
    slug: 'modal', title: 'Modal', summary: 'Creates a short focused surface that blocks background interaction and restores context on close.', useCases: ['Short confirmations and focused forms that return to the invoking task.'], importCode: "import { Modal } from '@/components'", basicCode: `<Modal open={open} onClose={close} title="Create project">…</Modal>`,
    props: [{ name: 'open', type: 'boolean', description: 'Controls whether the modal is present.' }, { name: 'onClose', type: '() => void', description: 'Handles permitted dismissal.' }, { name: 'title / description', type: 'string', description: 'Programmatic dialog name and optional description.' }, { name: 'footer', type: 'ReactNode', description: 'Right-aligned action row.' }, { name: 'initialFocusRef / returnFocusRef', type: 'RefObject<HTMLElement | null>', description: 'Overrides initial and restored focus targets.' }, { name: 'closeOnBackdrop / closeOnEscape', type: 'boolean', defaultValue: 'true', description: 'Configures safe dismissal.' }, { name: 'busy', type: 'boolean', defaultValue: 'false', description: 'Blocks dismissal while an essential operation is pending.' }, classNameProp],
    variants: ['Closed and open, with optional opening, busy, error, and closing content states.', 'Safe-dismiss and explicit-dismiss policies.'], accessibility: ['Uses the native modal dialog behavior for focus containment and background inertness.', 'Connects title and description; Escape follows the configured policy.', 'Closing restores focus to the invoking or captured element.'], responsive: 'Uses available width up to the narrow content token with viewport padding and vertical scrolling.', theme: 'Overlay, raised surface, secondary border, XL radius, and focus roles come from semantic tokens.', mistakes: ['Do not use for a full page or long multi-step task.', 'Disable backdrop dismissal when abandoning content could lose data.', 'Keep Cancel available for destructive confirmations.'], related: ['button', 'alert'],
  }),
  createDoc({
    slug: 'tabs', title: 'Tabs', summary: 'Switches between peer views of the same context with roving keyboard focus.', useCases: ['Overview, activity, and settings views of one entity.'], importCode: "import { Tabs } from '@/components'", basicCode: `<Tabs label="Project views" items={views} />`,
    props: [{ name: 'label', type: 'string', description: 'Accessible tab-list name.' }, { name: 'items', type: 'readonly TabItem[]', description: 'IDs, labels, panels, and optional disabled state.' }, { name: 'value / defaultValue', type: 'string', description: 'Controlled or initial selected tab.' }, { name: 'activation', type: "'automatic' | 'manual'", defaultValue: "'automatic'", description: 'Determines whether focus or an activation key selects.' }, { name: 'orientation', type: "'horizontal' | 'vertical'", defaultValue: "'horizontal'", description: 'Sets layout and arrow-key axis.' }, { name: 'onValueChange', type: '(value: string) => void', description: 'Reports selection.' }, classNameProp],
    variants: ['Horizontal and vertical.', 'Automatic and manual activation.', 'Default, hover, focus, selected, and disabled states.'], accessibility: ['Implements tablist, tab, and tabpanel relationships with managed tab stops.', 'Arrow keys, Home, and End move focus; Enter or Space selects in manual mode.', 'A line indicator supplements selected color.'], responsive: 'Horizontal tabs scroll in a contained region rather than wrapping into ambiguous rows.', theme: 'Default, hover, selected, focus, surface, and indicator colors use semantic tokens.', mistakes: ['Do not use tabs for global navigation or sequential steps.', 'Do not use automatic activation if panels load slowly.', 'Keep selection and focus conceptually distinct.'], related: ['navigation'],
  }),
  createDoc({
    slug: 'table', title: 'Table', summary: 'Presents relational data with native row and column semantics, sorting, and optional selection.', useCases: ['Scannable records where comparison across columns matters.'], importCode: "import { Table } from '@/components'", basicCode: `<Table caption="Projects" columns={columns} rows={rows} getRowId={(row) => row.id} />`,
    props: [{ name: 'caption', type: 'string', description: 'Accessible table name.' }, { name: 'columns', type: 'readonly TableColumn<T>[]', description: 'Headers, cell renderers, numeric alignment, and sortable state.' }, { name: 'rows / getRowId', type: 'readonly T[] / (row: T) => string', description: 'Data and stable row identity.' }, { name: 'sort / onSort', type: 'Sort state / callback', description: 'Controlled active sort and direction.' }, { name: 'selectedRowIds / onSelectionChange', type: 'readonly string[] / callback', description: 'Optional explicit row selection.' }, { name: 'loading / error / emptyMessage', type: 'boolean / ReactNode / ReactNode', description: 'Distinct data availability states.' }, { name: 'toolbar', type: 'ReactNode', description: 'Optional labelled controls above the table.' }, classNameProp],
    variants: ['Static and selectable data tables.', 'Sorted, loading, empty, error, selected, and hover states.'], accessibility: ['Uses native table, caption, headers, cells, and aria-sort.', 'Selection controls include record context.', 'Numeric cells use consistent alignment and tabular numerals.'], responsive: 'Prioritizes data, then uses contained horizontal scrolling without forcing page overflow.', theme: 'Header, row, hover, selected, and boundary tokens map directly to the table contract.', mistakes: ['Do not apply grid semantics without managed cell navigation.', 'Do not make whole rows ambiguous actions.', 'Do not remove headers while refreshing.'], related: ['data-grid', 'status-badge'],
  }),
  createDoc({
    slug: 'data-grid', title: 'Data grid', summary: 'Adds managed two-dimensional focus, row selection, and optional cell editing to tabular data.', useCases: ['Large datasets where people need efficient cell navigation, selection, or inline editing.'], importCode: "import { DataGrid } from '@/components'", basicCode: `<DataGrid label="Projects" columns={columns} rows={rows} getRowId={(row) => row.id} />`,
    props: [{ name: 'label', type: 'string', description: 'Accessible grid name.' }, { name: 'columns', type: 'readonly DataGridColumn<T>[]', description: 'Cell renderers and optional editor renderers.' }, { name: 'rows / getRowId', type: 'readonly T[] / (row: T) => string', description: 'Data and stable identity.' }, { name: 'selectable', type: 'boolean', defaultValue: 'false', description: 'Enables Space-based row selection.' }, { name: 'selectedRowIds / onSelectionChange', type: 'readonly string[] / callback', description: 'Controlled selection.' }, { name: 'loading / emptyMessage', type: 'boolean / ReactNode', description: 'Data availability state.' }, classNameProp],
    variants: ['Read-only, selectable, and editable cells.', 'Focused, selected, editing, loading, and empty states.'], accessibility: ['Only one cell is in the page tab sequence.', 'Arrow keys move between cells; Home and End move within the row.', 'Enter enters configured edit mode, Escape exits, and Space selects a row.'], responsive: 'Keeps grid navigation intact inside contained horizontal scrolling; prioritize essential columns first.', theme: 'Shares table roles while focus, selection, and validation remain distinct.', mistakes: ['Use Table when managed cell navigation is unnecessary.', 'Do not add grid semantics just to reduce tab stops.', 'Provide non-drag alternatives for resizing or rearranging.'], related: ['table', 'input'],
  }),
  createDoc({
    slug: 'status-badge', title: 'Status badge', summary: 'Communicates persistent entity or workflow state with a required text label.', useCases: ['Active, pending, blocked, in-review, and draft states.'], importCode: "import { StatusBadge } from '@/components'", basicCode: `<StatusBadge variant="positive">Active</StatusBadge>`,
    props: [{ name: 'variant', type: "'positive' | 'warning' | 'negative' | 'info' | 'neutral'", defaultValue: "'neutral'", description: 'Maps persistent meaning to the correct status token family.' }, { name: 'icon', type: 'ReactNode', description: 'Optional decorative icon; text remains required.' }, { name: 'children', type: 'ReactNode', description: 'Required visible status label.' }, { name: '…span props', type: 'HTMLAttributes<HTMLSpanElement>', description: 'Forwards non-interactive span attributes.' }, classNameProp],
    variants: ['Positive, warning, negative, info, and neutral.', 'Informational only—no hover, focus, or active states.'], accessibility: ['Always include text; icons or dots are supplementary.', 'Important dynamic changes use surrounding announcement logic rather than making every badge live.', 'The component intentionally has no interaction semantics.'], responsive: 'Preserves the label on narrow screens rather than collapsing to an unexplained dot.', theme: 'Each variant uses its matching status foreground, background, and border roles.', mistakes: ['Do not use for transient operation feedback.', 'Do not make the badge itself a filter or link.', 'Do not communicate status by color alone.'], related: ['alert', 'table'],
  }),
  createDoc({
    slug: 'alert', title: 'Alert', summary: 'Communicates contextual information, warnings, outcomes, failures, and available recovery.', useCases: ['Inline notices, save confirmation, warnings, and recoverable errors.'], importCode: "import { Alert } from '@/components'", basicCode: `<Alert variant="success" title="Changes saved">Settings are current.</Alert>`,
    props: [{ name: 'variant', type: "'success' | 'warning' | 'danger' | 'info'", defaultValue: "'info'", description: 'Sets the feedback—not status—meaning.' }, { name: 'title', type: 'ReactNode', description: 'Concise summary.' }, { name: 'urgent', type: 'boolean', defaultValue: 'false', description: 'Uses an urgent alert announcement instead of status.' }, { name: 'action', type: 'ReactNode', description: 'Optional recovery or next action.' }, { name: 'dismissible / onDismiss', type: 'boolean / () => void', description: 'Adds a labelled close action and notification.' }, { name: 'children', type: 'ReactNode', description: 'Message body.' }, classNameProp],
    variants: ['Success, warning, danger, and info.', 'Current, dismissible, urgent, non-urgent, and resolved states.'], accessibility: ['New urgent messages use alert; non-urgent updates use status.', 'The semantic icon and text provide non-color severity cues.', 'Dismiss controls are labelled with alert context.'], responsive: 'Content and actions wrap; actions can stack below the message in constrained space.', theme: 'Uses feedback foreground, background, and border roles—not persistent status roles.', mistakes: ['Do not mark routine static guidance urgent.', 'Do not dismiss the only recovery path.', 'Do not use a status badge for a transient failure.'], related: ['status-badge', 'button'],
  }),
  createDoc({
    slug: 'dropdown', title: 'Dropdown', summary: 'Provides the shared raised popup surface as an accessible action-menu implementation.', useCases: ['Short command menus such as Rename, Duplicate, Archive, and Delete.'], importCode: "import { Dropdown } from '@/components'", basicCode: `<Dropdown label="Project actions" items={actions} />`,
    props: [{ name: 'label', type: 'string', description: 'Visible trigger label and menu name.' }, { name: 'items', type: 'readonly DropdownItem[]', description: 'Commands with stable IDs, labels, availability, and handlers.' }, { name: 'buttonProps', type: 'Omit<ButtonProps, controlled trigger props>', description: 'Configures the real Button trigger.' }, { name: 'align', type: "'start' | 'end'", defaultValue: "'start'", description: 'Aligns the popup to a trigger edge.' }, classNameProp],
    variants: ['Action menu with normal, destructive, and disabled commands.', 'Closed and open states with active item focus.'], accessibility: ['Trigger exposes menu popup and expanded state.', 'Arrow keys, Home, End, Escape, Tab, and native activation are supported.', 'Escape closes and restores trigger focus; outside activation dismisses.'], responsive: 'The menu sizes to content; use a dialog or bottom sheet if touch targets cannot fit the viewport.', theme: 'Uses raised surface, quiet boundary, tertiary hover/focus, danger text, and focus tokens.', mistakes: ['Dropdown is not one universal behavior.', 'Use Listbox for selection and Combobox for editable suggestions.', 'Do not assign menu roles to ordinary navigation.'], related: ['button', 'listbox', 'combobox'],
  }),
  createDoc({
    slug: 'navigation', title: 'Navigation shell', summary: 'Provides stable destinations, global utilities, a collapsible desktop sidebar, and modal mobile navigation.', useCases: ['Application and admin shells where navigation must coexist with a fluid workspace.'], importCode: "import { NavigationShell } from '@/components'", basicCode: `<NavigationShell brand="Bento" items={items} currentHref={pathname}>…</NavigationShell>`,
    props: [{ name: 'brand', type: 'ReactNode', description: 'Product or system identity.' }, { name: 'items', type: 'readonly NavigationItem[]', description: 'Stable destination labels, hrefs, and optional icons.' }, { name: 'currentHref', type: 'string', description: 'Marks the current destination programmatically and visually.' }, { name: 'utilities', type: 'ReactNode', description: 'Account, help, notifications, or global actions.' }, { name: 'collapsed / onCollapsedChange', type: 'boolean / callback', description: 'Controlled or internal desktop sidebar state.' }, { name: 'navigationLabel', type: 'string', defaultValue: "'Primary navigation'", description: 'Names the navigation landmark and mobile dialog.' }, classNameProp],
    variants: ['Expanded and collapsed persistent sidebar.', 'Temporary modal navigation at compact widths.', 'Default, hover, focus, and current destination states.'], accessibility: ['Uses named navigation landmarks and aria-current.', 'Collapsed links retain names through title and accessible text.', 'Mobile navigation moves focus inside, contains it, closes on Escape, and restores the trigger.'], responsive: 'At compact widths the sidebar becomes temporary navigation; at expanded widths it preserves workspace priority.', theme: 'Sidebar, item, selected, topbar, boundary, and focus roles map directly to navigation tokens.', mistakes: ['Do not style the current route as a primary action.', 'Do not remove destination names from the accessible tree when collapsed.', 'Do not place a squeezed persistent sidebar beside a narrow workspace.'], related: ['tabs', 'button'],
  }),
  createDoc({
    slug: 'card', title: 'Card', summary: 'Groups related content when a quiet boundary materially improves comprehension.', useCases: ['Bounded summaries, project groups, and compact metric or statistic cards.'], importCode: "import { Card, StatCard } from '@/components'", basicCode: `<Card heading={<h2>Project brief</h2>}>…</Card>`,
    props: [{ name: 'compact', type: 'boolean', defaultValue: 'false', description: 'Uses compact padding and radius.' }, { name: 'heading / footer', type: 'ReactNode', description: 'Optional structured header and footer regions.' }, { name: 'as', type: "'article' | 'section'", defaultValue: "'section'", description: 'Chooses the semantic container.' }, { name: 'label / value / metadata', type: 'StatCard props', description: 'Statistic-card content with tabular numeric emphasis.' }, { name: '…element props', type: 'HTMLAttributes<HTMLElement>', description: 'Forwards semantic element attributes.' }, classNameProp],
    variants: ['Standard, compact, and statistic cards.', 'Static by default; loading, empty, and error content follow data-display patterns.'], accessibility: ['Choose a section or article and preserve heading hierarchy.', 'A static card has no interaction or hover state.', 'Whole-card actions must not contain conflicting nested controls.'], responsive: 'Card grids reflow before values or labels become hard to scan.', theme: 'Uses primary surface, quiet boundary, semantic text, radii, and spacing roles.', mistakes: ['Do not wrap every region in a card.', 'Do not use elevation to imply missing interaction.', 'Keep multiple actions separate instead of making the whole card clickable.'], related: ['status-badge', 'table'],
  }),
] as const satisfies readonly ComponentDocumentation[]

export const componentDocsBySlug = new Map(componentDocs.map((component) => [component.slug, component]))
